---
- hosts: servers
  vars_files:
    - defaults/main.yml

  remote_user: "{{ system_user }}"
  become: yes
  gather_facts: true
  serial: 1

  vars_prompt:

    - name: domain
      prompt: "\n------
              \n\nSpecify WordPress URL"
      private: no
      default: "wordpress.local"

    - name: wp_version
      prompt: "\n------
              \n\nSpecify WordPress version you'd like to use"
      private: no
      default: "5.0.3"

    - name: wp_db_name
      prompt: "\n------
              \n\nSpecify WordPress database name"
      private: no
      default: "wordpress"

    - name: wp_db_tb_pre
      prompt: "\n------
              \n\nSpecify WordPress table prefix"
      private: no
      default: "wp_"

    - name: wp_db_psw
      prompt: "\n------
              \n\nSpecify WordPress database password"
      private: yes
      default: "^3#6QKvj"
      confirm: yes

  roles:
  - debian
  - security 
  - wordpress
